apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -automation-node

commonLabels:
  app: dss-automation-node

images:
  - name: dss-node-image
    newName: registry.gitlab.com/tibor_fabian/dku-dss-k8s/dss-automation-node
    newTag: dss-8.0.2-2020.10.26-07.25.42

configMapGenerator:
  - name: dss-node-type
    literals:    
    - DSS_NODE_TYPE=automation

bases:
  - ../base

patchesStrategicMerge:
  - resources.yaml
  - volumes.yaml