apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -design-node-installation

commonLabels:
  app: dss-design-node

configMapGenerator:
  - name: dss-node-type
    literals:    
    - DSS_NODE_TYPE=design

bases:
  - ../base

patchesStrategicMerge:
  - volume.yaml
