apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: design-node
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
