apiVersion: v1
kind: PersistentVolume
metadata:
  name: design-node
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/dss
