apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -automation-node-installation

commonLabels:
  app: dss-automation-node

configMapGenerator:
  - name: dss-node-type
    literals:    
    - DSS_NODE_TYPE=automation

bases:
  - ../base

patchesStrategicMerge:
  - volume.yaml
