apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -apideployer-node-installation

commonLabels:
  app: dss-apideployer-node

configMapGenerator:
  - name: dss-node-type
    literals:    
    - DSS_NODE_TYPE=apideployer

bases:
  - ../base

patchesStrategicMerge:
  - volume.yaml
