apiVersion: v1
kind: Pod
metadata:
    name: dss
spec:
    containers:
      - name: dss
        volumeMounts:
          - name: dss-data
            mountPath: /media/dss-apideployer-node

    volumes:
      - name: dss-data
        hostPath:
          path: /Users/tiborfabian/dss/apideployer-node