apiVersion: apps/v1
kind: Deployment
metadata:
  name: dss
spec:
  template:
    spec:
      containers:
        - name: dss
          resources:
            requests:
              cpu: 1
              memory: 4Gi
            limits:
              cpu: 1
              memory: 4Gi
