apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -design-node

commonLabels:
  app: dss-design-node

images:
  - name: dss-node-image
    newName: registry.gitlab.com/tibor_fabian/dku-dss-k8s/dss-design-node
    newTag: dss-8.0.3-2020.11.28-09.49.33

configMapGenerator:
  - name: dss-node-type
    literals:    
    - DSS_NODE_TYPE=design

bases:
  - ../base

patchesStrategicMerge:
  - resources.yaml
  - volumes.yaml